import { useEffect, useState } from "react";
import { Activity, Car, CheckCircle2, ClipboardList, FileText, MessageSquare, UserCog, Users, Warehouse } from "lucide-react";
import "./Dashboard.css";

interface DashboardStats{total_users:number;total_drivers:number;available_drivers:number;total_vehicles:number;total_vendors:number;total_bookings:number;pending_bookings:number;total_trips:number;ongoing_trips:number;completed_trips:number;total_invoices:number;total_feedback:number}
interface StatCardProps{title:string;value:number;subtitle?:string;icon:React.ComponentType<{size?:number;strokeWidth?:number}>}
function StatCard({title,value,subtitle,icon:Icon}:StatCardProps){return <div className="stat-card"><div className="stat-card-top"><div><h3>{title}</h3><div className="stat-number">{value}</div>{subtitle&&<p>{subtitle}</p>}</div><div className="stat-icon"><Icon size={20}/></div></div></div>}
function Dashboard(){
 const [stats,setStats]=useState<DashboardStats|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{let cancelled=false; const load=async()=>{try{const token=localStorage.getItem("token");const response=await fetch(`${import.meta.env.VITE_API_URL}/dashboard/stats`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error("Failed to load dashboard statistics");const data:DashboardStats=await response.json();if(!cancelled){setStats(data);setError("");setLoading(false)}}catch(err){console.error(err);if(!cancelled){setError("Unable to load dashboard statistics");setLoading(false)}}};load();return()=>{cancelled=true}},[]);
 if(loading)return <div className="dashboard"><div className="dashboard-loading"><div className="loading-spinner"/><h2>Loading dashboard...</h2><p>Please wait while we load your dashboard data.</p></div></div>;
 if(error)return <div className="dashboard"><div className="dashboard-error-card"><div className="error-icon">!</div><h2>Unable to load dashboard</h2><p>{error}</p></div></div>;
 return <div className="dashboard"><div className="dashboard-header"><div><h1>Dashboard</h1><p>Welcome to your DOTRIP management dashboard.</p></div><div className="dashboard-status"><span className="status-dot"/>System Online</div></div>
 <div className="stats-grid"><StatCard title="Total Users" value={stats?.total_users??0} icon={Users}/><StatCard title="Drivers" value={stats?.total_drivers??0} subtitle={`${stats?.available_drivers??0} available`} icon={UserCog}/><StatCard title="Vehicles" value={stats?.total_vehicles??0} icon={Car}/><StatCard title="Vendors" value={stats?.total_vendors??0} icon={Warehouse}/><StatCard title="Bookings" value={stats?.total_bookings??0} subtitle={`${stats?.pending_bookings??0} pending`} icon={ClipboardList}/><StatCard title="Trips" value={stats?.total_trips??0} subtitle={`${stats?.ongoing_trips??0} ongoing`} icon={Activity}/><StatCard title="Completed Trips" value={stats?.completed_trips??0} icon={CheckCircle2}/><StatCard title="Invoices" value={stats?.total_invoices??0} icon={FileText}/><StatCard title="Feedback" value={stats?.total_feedback??0} icon={MessageSquare}/></div>
 <div className="dashboard-summary"><div className="summary-card"><div><span className="summary-label">Booking Status</span><h3>{stats?.pending_bookings??0} pending bookings</h3><p>Keep an eye on pending bookings and trip activity from this dashboard.</p></div><ClipboardList size={28}/></div><div className="summary-card"><div><span className="summary-label">Driver Availability</span><h3>{stats?.available_drivers??0} drivers available</h3><p>Monitor available drivers before assigning new trips.</p></div><UserCog size={28}/></div></div></div>;
}
export default Dashboard;
